### ISSUE TITLE
This is a title

### ISSUE THREAD

**Issue by XDean** [zhangysh1995/RMIwheel#1]
你好，yushan，我快速地看了以下你的代码，想问一下你是用什么思路做的远程调用？因为我看到你还是用了RMI的接口。我以前也做过类似的远程过程调用（一个基于HTTP的实现，但是时间久远，没有继续完善下去），如果有兴趣可以多交流。

**Comment by zhangysh1995** [comment]
> 你好，yushan，我快速地看了以下你的代码，想问一下你是用什么思路做的远程调用？因为我看到你还是用了RMI的接口。我以前也做过类似的远程过程调用（一个基于HTTP的实现，但是时间久远，没有继续完善下去），如果有兴趣可以多交流。

远程调用我了解的有两种方法：序列化和反射机制。
1. 自己手写一个 Server 端类的 Stub 对象，把这个对象发送给客户端。这个对象是根据你要实现的功能做过改造的，比如 login 这个功能其实就是一个接口，里面会和 Server 进行通信，处理远程调用的问题，然后把结果返回。
2. 使用反射机制建立一个 Proxy，自己重写 invocationHandler 这个接口，然后把这个 Proxy 发送给客户端。客户端拿到的这个 Proxy 就是自动生成的，当你调用 login 方法时，invocationHandler 里面写好的方法会和 Server 进行通信，然后把结果返回。

对比着两种方法：第一种需要手动区分每一个调用的方法名称，不能写一段代码处理所有的调用。第二种只需要重写一个接口，可以处理所有不同的远程调用。

我的代码里两种方法都有使用，可以参考 Server 模块里 ```SimpleRegistryServer```，```LocateSimpleRegistry``` 和 ```RemoteObjectRef 的代码```。项目的类图在 Resources 这个文件夹底下。

如果有别的想法欢迎提出！

**Comment by XDean** [comment]
几点建议
1.代码整洁，包括命名规范，包规范，代码结构（单个文件的结构），还有许多显然无用的注释
2.泛型，我看到几处可以用泛型来避免显式类型转化（事实上也是为了代码好看）
3.重载，在你的Proxy里，传出的是method.getName，你可以考虑下重载的情况，应该用什么呢
4.更多，考虑诸如涉及复杂对象的情况，抛出异常的情况等等
我刚刚上传了以前写的RPC框架，或许能对你有所帮助，XDean/RPC-HTTP

**Comment by zhangysh1995** [comment]
> 几点建议
> 1.代码整洁，包括命名规范，包规范，代码结构（单个文件的结构），还有许多显然无用的注释
> 2.泛型，我看到几处可以用泛型来避免显式类型转化（事实上也是为了代码好看）
> 3.重载，在你的Proxy里，传出的是method.getName，你可以考虑下重载的情况，应该用什么呢
> 4.更多，考虑诸如涉及复杂对象的情况，抛出异常的情况等等
> 我刚刚上传了以前写的RPC框架，或许能对你有所帮助，XDean/RPC-HTTP

这个作业是在老师给的代码上改的，所以一部分代码和注释是本身就有的，我也没有修改，但是这点我以后会注意。其他几个方面，我在以后的代码里会争取做到更好。我现在还是 Java 的初学者，对 Java 的很多用法还不是很熟悉，这个需要之后慢慢学习才能取得进步。谢谢你的建议。
